// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RejestrWydatkow.Models;

#nullable disable

namespace RejestrWydatkow.Migrations
{
    [DbContext(typeof(WydatkiDbContext))]
    [Migration("20250528230506_m3")]
    partial class m3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RejestrWydatkow.Models.Wydatek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kwota")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wydatek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kategoria = "Jedzenie",
                            Kwota = 150.75,
                            Opis = "Zakupy spożywcze"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kategoria = "Transport",
                            Kwota = 220.0,
                            Opis = "Paliwo"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kategoria = "Rozrywka",
                            Kwota = 45.0,
                            Opis = "Kino"
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kategoria = "Subskrypcje",
                            Kwota = 55.0,
                            Opis = "Abonament Netflix"
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kategoria = "Media",
                            Kwota = 300.0,
                            Opis = "Rachunek za prąd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
